language: go
go:
- 1.9
install:
- go get -v github.com/Masterminds/glide
- cd $GOPATH/src/github.com/Masterminds/glide && git checkout 245caced2b16358b1c5e267691b17e9ee9952127
  && go install && cd -
- glide install
script:
- go build -a -v -tags 'netgo' -o aws-account-alias main.go
deploy:
  provider: releases
  api_key:
    secure: Zf1lGlLyL3iGSSj6Ql7pz+nQkbXJ79WXl0lZUQqkIjggSezAWg2ZlmtEN3tobqgpnl8I1i139y4LtffNICRmzVWgdKEQbRVq7CSiJcOqdBsh8AbJxOAX1EfR4527YORkbngVxDVpleiRK7XTrkAIK0V7odKwvk5+8MgN4G0PmETcNNOvXp+65jHaxWC+8SmFynb4lzlhRdfO/8LApvR2Qz3X07U/li/jE4JeTZQP5zly5xZviOMh/BRTmoXjNtfkdV5sdE/eoqGHfC13mAdljxVJFJ6B1dI+VWIYw7BABQ0m1yJHfAgcVaewH4UT+XEY/4hKurhrgrNNgbT85Jgwy965BG/piGZMvSCAXp9GInwsNypl7u4DP8tO/Jyydx1W6vniTrL/snRDiw9JTsXQ8O9WMmxR65eocfPp7zkb+0sHaUGdB891OmPrOT4FUB+YnlyVstsIsL/uz8MdkSo4uOuLAaquhO3c4GYfAQVBtYqVOFm7R9BwvOqfr7RwSmCZZtsAtiB4sjECS3055jZ/ZFtzgDjgCPlq7GJGdeR9lvosNVInZSbtP/6YiQBUpM25kHuFvxDxEyFcrpV4XGvY7NnZdUTEMFjjOFA4TX1ZccL3DVXDkFeCy0TRGkuXeN6fhGVSr1sVITd2s2nmWq097bV4PL2dUsrLJpK1TaxAC3c=
  file: "aws-account-alias"
  skip_cleanup: true
  on:
    tags: true
    repo: securityscorecard/aws-account-alias
